### ISSUE TITLE
I want to know the usage of persona_map

### ISSUE THREAD

**Issue by leyi-123** [HLTCHKUST/PAML#14]
What is the purpose of data_analysis.ipynb？Is it necessary for the code?Is there another way to get persona_map file?

**Comment by andreamad8** [comment]
Hi,

This file is just used to create the meta-training set, so just by clustering the personas. 

Andrea

**Comment by leyi-123** [comment]
> 
> 
> Hi,
> 
> This file is just used to create the meta-training set, so just by clustering the personas.
> 
> Andrea

I see, thanks! And I also want to know if I can train this model successfully without persona_map? Meanwhile, are there any requires for the number of the clustering persona?

**Comment by andreamad8** [comment]
Hi, 

what do you mean without persona_map?

And yes, so we use 1K/1.2K cause in the original dataset they mention to have 1K different personas.

**Comment by leyi-123** [comment]
> 
> 
> Hi,
> 
> what do you mean without persona_map?
> 
> And yes, so we use 1K/1.2K cause in the original dataset they mention to have 1K different personas.

Thanks for your help! The total question is raised in my latest issue, so let's go there and discuss it!
