### ISSUE TITLE
How you compute the second order optimization partial derivatives ?

### ISSUE THREAD

**Issue by jcyk** [HLTCHKUST/PAML#17]
Hi, Thanks for open-sourcing your awesome work!

I just got a little confused. In the paper, you mentioned that "This process requires ***second order*** optimization partial derivatives, which can be computed by any automatic differentiation library". 

However, I did not find any code related to  ***second order*** derivatives. Am I missing something? could you please kindly point out how you compute the second order derivatives?

**Comment by zlinao** [comment]
Hi, thanks for the questions.

Yes, you are right. In this repo, we only implement the first-order approximation.

**Comment by jcyk** [comment]
@zlinao Great! thank you very much for your quick response.
