### ISSUE TITLE
Some doubts about the dataset

### ISSUE THREAD

**Issue by peizhao-rs** [HLTCHKUST/PAML#2]
I'd like to use the same dataset to train another persona chatbot model, but I have no idea what the cand mean in the train set. What's the association between cand and u/r ?

**Comment by andreamad8** [comment]
So this is related to the original Persona dataset, where each user response (r) has also 10 possible candidate answers. The dataset file was structured as follow:
id \t u \t r \t c1 | c2 | .... | c10

6 hello , how are you doing tonight ?	i am well an loving this interaction how are you ?		god help you and make you rich one day .|it is okay . nothing special !|do you live in a large or small city ? i am in large|i like blue hair . is it dark blue or light blue ?|hey ! coach johnny here ! how are you|great ! i do work on my fathers hobby farm in my spare time|yes ! one photo is going in an ad at my agency too|i try to go to the gym every once in a while|that is so nice ! i wanted girls but have two boys . would not trade them , though !|no , i like to watch tv shows . the office is my favorite|you re awesome i hope i can do that|wish i could . i keep a large garden as well .|the office i think if ok ; i am not sure about the latter .|i love the gym , i go daily .|have two cats . do you travel a lot ?|i knit baby hats for local hospitals !|yeah swimming is really fun , works everything out|about 70 , 000 but the more you make the more you spend i need to cut back|hi , how are you doing ?|i am well an loving this interaction how are you ?

In our model we didn't use the candidate list. 

I hope this help.

**Comment by peizhao-rs** [comment]
Thanks a lot for your reply.
